version: 1.0.{build}
build_script:
- ps: >-
    dotnet restore

    dotnet build

environment:
  COVERALLS_REPO_TOKEN:
    secure:  pPmHN6v5zSXvrCwMprQRQzA6bwTBgHsYU

test_script:
- ps: dotnet test test/Reusables.Test.csproj